### ISSUE TITLE
Potential solution to context menu option

### ISSUE THREAD

**Issue by haojunsui** [Aireil/FFLogsViewer#19]
I cam across this plugin (https://github.com/electr0sheep/ItemVendorLocation) on GitHub and it does enable new context menu item upon right clicking items in inventory. Based on their issue history, it looks like they even once had context menu item enabled for all menu types (including characters). Since their plugin is up-to-date with Dalamud, maybe we could find workaround using their approach.
![image](https://user-images.githubusercontent.com/6809863/165008663-f1000f41-1848-4707-bbd2-bbe7a7367182.png)

**Comment by Aireil** [comment]
Have you tested it? Because it's using the old library I was using as well, but the context menu feature got removed of that library to be added to Dalamud.
Unfortunately, Dalamud's implementation has some issues and people are reporting sporadic crashes when opening context menus.

The current version of my plugin already supports Dalamud's implementation, they are just disabled by default. If you don't mind the rare risk of crashing when opening one, you can just set the environment variable `DALAMUD_NO_CONTEXTMENU` to true before starting the game.

**Comment by Aireil** [comment]
Correction: The env var is `DALAMUD_ENABLE_CONTEXTMENU` to true, what I sent was a precious one.

**Comment by haojunsui** [comment]
I'm using that plugin for a while right now and context menu doesn't seem to crash. Setting the global variable setting seems to be simple enough to bypass the restriction for now.

**Comment by Aireil** [comment]
Just tested the plugin you linked and it indeed works with an old version of the library.
There are now plans to replace Dalamud's implementation with it soon. If it doesn't happen, I'll add that old library back.

Thank you for the info!
