### ISSUE TITLE
add a header or encounter for trial unreal in layout for every auto updates

### ISSUE THREAD

**Issue by Bos-hunting** [Aireil/FFLogsViewer#28]
I know that users can add encounters for trial unreal manually. But the auto-layout update won't function if users add new encounters manually. Is it possible to see the unreal trial as well as other savage and ultimate in the upcoming every patch update?

**Comment by Aireil** [comment]
I'm not planning on adding unreal to the default layout again, because I've had multiple feedbacks concerning it and with the addition of each new ultimate, the layout is getting longer and longer.
I will say the process of adding fights has been significantly improved over the "recentish" versions and should now pretty much be 10 clicks max if you're adding a savage tier and a trial, which doesn't happen that frequently.
Therefore, having a custom layout shouldn't really be a hassle, although if you find something that could be improved about this, feel free to suggest it.

**Comment by Bos-hunting** [comment]
Gotcha thanks!
