### ISSUE TITLE
[Suggestion] For Party View, an option for Selected Job, so it shows the parse for the currently selected job of each party member

### ISSUE THREAD

**Issue by imgidedin** [Aireil/FFLogsViewer#35]
As title says, an option to show the parse for the current job for each party member. Right now, it shows the best one (when all jobs is selected), but more often than not, people are playing alt jobs. Would be nice to know how they perform with said job, instead of having to manually select the job just to see the stats for one player, and repeat that more times for each party member.

**Comment by Aireil** [comment]
Added to 2.1.5.2, which is currently deploying, the default can be changed in Configuration -> Stats.
In party view it shows the loaded job color on the names, in single view, it colors the "Current job" in the menu bar.

![image](https://github.com/Aireil/FFLogsViewer/assets/33433913/26c9de77-b35e-4099-8179-edc42cd85dd2)

**Comment by imgidedin** [comment]
![image](https://github.com/Aireil/FFLogsViewer/assets/19570528/1fbaa923-6d39-448b-8cdb-2f0826624b4c)
![image](https://github.com/Aireil/FFLogsViewer/assets/19570528/f8ef1647-d09e-4da4-aab3-d59cab5ec3a6)

It doesnt work if the party member is not in the same place as you (on xworld parties). It tries to search for your current job instead. If the player is near you, it will work.

Below, an example of someone in the same region:

![image](https://github.com/Aireil/FFLogsViewer/assets/19570528/d5a7c797-22d7-4528-a589-799ef9050ad1)
![image](https://github.com/Aireil/FFLogsViewer/assets/19570528/5880631e-dcf8-4d2d-bb2a-939f71657548)

**Comment by Aireil** [comment]
> It tries to search for your current job instead.
I couldn't reproduce this, it seemed to search for a stale job set earlier, but not your current job? Although it's probably fixed anyway with the other changes.

> If the player is near you, it will work.
Yes, that was by design, I was just looking around for single view, but I've changed that behavior to check in the party list as well if it can't find the player. It will still not work for normal parties when someone is in a different zone, as the game party list doesn't know their job.

These changes are in 2.1.5.3 which is deploying now.
