### ISSUE TITLE
Fix for dalamud scaling

### ISSUE THREAD

**Issue by Iaotle** [Aireil/FFLogsViewer#4]
Plugin breaks when dalamud scaling is more than 1. This is what it looks like on 1.5:
![image](https://user-images.githubusercontent.com/43072246/147780199-937d4676-d2d2-40ee-a34a-8627230f1082.png)

Should be easy to fix with a resizable window.

**Comment by Aireil** [comment]
I cannot make the window resizable because nearly everything is manually placed, which isn't ideal, to say the least.
The plugin has not been designed with scaling in mind, I want to rewrite it completely when I have the time / motivation.

I've pushed an update to help a bit. It's far from perfect, but should be usable.
